name: warehouse_management
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_database: ^11.3.0 # Para o banco de dados
  firebase_storage: ^12.4.0  # Para as fotos
  image_picker: ^1.1.2       # Para tirar/selecionar fotos
  provider: ^6.1.2          # Gerenciamento de estado
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.1
  firebase_app_installations: ^0.3.2
  intl: ^0.20.1
  image: ^4.0.15

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - ios/Assets/stock_out.png
    - ios/Assets/logo_cliente.png
